# Generated by Django 4.1.3 on 2022-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='Media/featured_img')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
