# Generated by Django 4.1.3 on 2022-11-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_level_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semi_des',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
