# Generated by Django 4.1.3 on 2022-11-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lesson_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
