# Generated by Django 4.1.3 on 2022-11-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='about_author',
            new_name='about_instructor',
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
