# Generated by Django 4.1.3 on 2022-11-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('review_course', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
